env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:jsx-a11y/recommended"
  - "plugin:react-hooks/recommended"
  - "next"
  - "next/core-web-vitals"
  - "prettier"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
rules:
  {
    "@next/next/no-img-element": 0,
    "no-undef": 0,
    "react-hooks/exhaustive-deps": 0,
    "jsx-a11y/anchor-is-valid": 0,
    "import/no-unresolved": 0,
  }
settings:
  linkComponents:
    - name: Link
      linkAttribute: href
  react:
    version: detect
